bind 0.0.0.0
port 6379
protected-mode no
timeout 0
tcp-keepalive 300

dir /data
dbfilename dump.rdb

save 900 1
save 300 10
save 60 10000

appendonly yes
appendfilename "appendonly.aof"

loglevel notice
