export const PERMISSIONS = {
  viewLanding: "view:landing",
  viewAbout: "view:about",
  viewContact: "view:contact",
  viewPublicArticle: "view:article:public",
  viewInternalArticle: "view:article:internal",
  comment: "create:comment",
  manageOwnPrayers: "manage:prayer:own",
  shareChurchPrayers: "share:prayer:church",
  moderateChurchPrayers: "moderate:prayer:church",
  enrollCourses: "enroll:course",
  accessLessons: "access:lesson",
  takeAssessments: "take:assessment",
  viewCertificates: "view:certificate",
  viewEvents: "view:event",
  personalizedSearch: "search:personalized",
  manageArticle: "manage:article",
  manageLanding: "manage:landing",
  manageAbout: "manage:about",
  manageContact: "manage:contact",
  manageCourses: "manage:course",
  enrollMembers: "enroll:member",
  manageEvents: "manage:event",
  manageTelegramNotifications: "manage:telegram-notification",
  manageChurchMembers: "manage:church-member",
  createChurchMembers: "create:church-member",
  updateChurchMembers: "update:church-member",
  deleteChurchMembers: "delete:church-member",
  manageChurchUnits: "manage:church-unit",
  createChurchUnits: "create:church-unit",
  updateChurchUnits: "update:church-unit",
  deleteChurchUnits: "delete:church-unit",
  manageRoleSchemas: "manage:role-schema",
  manageSystemSettings: "manage:system-setting",
  manageIntegrations: "manage:integration",
  manageDatabaseConfig: "manage:database-config",
  viewAllData: "view:data:all",
  executeMaintenance: "execute:maintenance",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
